ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080

    database:
        url: "jdbc:postgresql://localhost:5432/tasksdatabase"
        driver: "org.postgresql.Driver"
        user: "tasksUser"
        password: "taskspassword"
